# Generated by Django 6.0.5 on 2026-05-30 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('work_location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sponsored', models.BooleanField(default=False)),
                ('visa_type', models.CharField(blank=True, max_length=100, null=True)),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('right_to_work_check_date', models.DateField(blank=True, null=True)),
                ('cos_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Certificate of Sponsorship number')),
                ('soc_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='SOC code')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weekly_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.company')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
